export interface District {
  name: string;
  cities: string[];
}

export interface State {
  name: string;
  districts: District[];
}

export const INDIAN_STATES: State[] = [
  {
    name: "Andhra Pradesh",
    districts: [
      { name: "Anantapur", cities: ["Anantapur", "Hindupur", "Kadiri", "Tadipatri"] },
      { name: "Chittoor", cities: ["Chittoor", "Tirupati", "Madanapalle", "Punganur"] },
      { name: "East Godavari", cities: ["Kakinada", "Rajahmundry", "Amalapuram", "Ramachandrapuram"] },
      { name: "Guntur", cities: ["Guntur", "Tenali", "Narasaraopet", "Mangalagiri"] },
      { name: "Krishna", cities: ["Vijayawada", "Machilipatnam", "Gudivada", "Jaggayyapeta"] },
      { name: "Kurnool", cities: ["Kurnool", "Nandyal", "Adoni", "Dhone"] },
      { name: "Prakasam", cities: ["Ongole", "Chirala", "Markapur", "Kandukur"] },
      { name: "Srikakulam", cities: ["Srikakulam", "Amadalavalasa", "Palasa", "Narasannapeta"] },
      { name: "Visakhapatnam", cities: ["Visakhapatnam", "Anakapalle", "Bheemunipatnam", "Narsipatnam"] },
      { name: "Vizianagaram", cities: ["Vizianagaram", "Bobbili", "Parvathipuram", "Salur"] },
      { name: "West Godavari", cities: ["Eluru", "Bhimavaram", "Tadepalligudem", "Tanuku"] },
    ]
  },
  {
    name: "Arunachal Pradesh",
    districts: [
      { name: "Tawang", cities: ["Tawang", "Jang", "Lumla"] },
      { name: "West Kameng", cities: ["Bomdila", "Nafra", "Rupa"] },
      { name: "East Kameng", cities: ["Seppa", "Chayangtajo"] },
      { name: "Papum Pare", cities: ["Yupia", "Naharlagun", "Nirjuli"] },
      { name: "Lower Subansiri", cities: ["Ziro", "Hapoli", "Yachuli"] },
      { name: "Upper Subansiri", cities: ["Daporijo", "Dumporijo"] },
      { name: "West Siang", cities: ["Aalo", "Basar", "Tato"] },
      { name: "East Siang", cities: ["Pasighat", "Mebo", "Ruksin"] },
      { name: "Upper Siang", cities: ["Yingkiong", "Tuting"] },
      { name: "Changlang", cities: ["Changlang", "Miao", "Nampong"] },
      { name: "Tirap", cities: ["Khonsa", "Deomali", "Bordumsa"] },
      { name: "Longding", cities: ["Longding", "Kanubari", "Pongchau"] },
      { name: "Lohit", cities: ["Tezu", "Namsai", "Chowkham"] },
      { name: "Anjaw", cities: ["Hawai", "Hayuliang", "Manchal"] },
      { name: "Dibang Valley", cities: ["Anini", "Roing"] },
      { name: "Lower Dibang Valley", cities: ["Roing", "Dambuk", "Desali"] },
      { name: "Kurung Kumey", cities: ["Koloriang", "Parsi Parlo", "Sangram"] },
    ]
  },
  {
    name: "Assam",
    districts: [
      { name: "Baksa", cities: ["Mushalpur", "Barama", "Tamulpur"] },
      { name: "Barpeta", cities: ["Barpeta", "Sorbhog", "Howly"] },
      { name: "Bongaigaon", cities: ["Bongaigaon", "Abhayapuri", "Jogighopa"] },
      { name: "Cachar", cities: ["Silchar", "Hailakandi", "Lakhipur"] },
      { name: "Chirang", cities: ["Kajalgaon", "Bijni", "Sidli"] },
      { name: "Darrang", cities: ["Mangaldoi", "Kharupetia", "Dalgaon"] },
      { name: "Dhemaji", cities: ["Dhemaji", "Jonai", "Sissiborgaon"] },
      { name: "Dhubri", cities: ["Dhubri", "Gauripur", "Bilasipara"] },
      { name: "Dibrugarh", cities: ["Dibrugarh", "Naharkatiya", "Tinsukia"] },
      { name: "Goalpara", cities: ["Goalpara", "Dudhnoi", "Lakhipur"] },
      { name: "Golaghat", cities: ["Golaghat", "Bokakhat", "Sarupathar"] },
      { name: "Hailakandi", cities: ["Hailakandi", "Lala", "Katlicherra"] },
      { name: "Jorhat", cities: ["Jorhat", "Titabar", "Mariani"] },
      { name: "Kamrup", cities: ["Guwahati", "Rangia", "Hajo"] },
      { name: "Kamrup Metropolitan", cities: ["Guwahati", "Dispur"] },
      { name: "Karbi Anglong", cities: ["Diphu", "Bokajan", "Howraghat"] },
      { name: "Karimganj", cities: ["Karimganj", "Badarpur", "Nilambazar"] },
      { name: "Kokrajhar", cities: ["Kokrajhar", "Gossaigaon", "Dotma"] },
      { name: "Lakhimpur", cities: ["North Lakhimpur", "Dhakuakhana", "Bihpuria"] },
      { name: "Marigaon", cities: ["Marigaon", "Laharighat", "Jagiroad"] },
      { name: "Nagaon", cities: ["Nagaon", "Hojai", "Lanka"] },
      { name: "Nalbari", cities: ["Nalbari", "Tihu", "Mukalmua"] },
      { name: "Sivasagar", cities: ["Sivasagar", "Nazira", "Amguri"] },
      { name: "Sonitpur", cities: ["Tezpur", "Biswanath Chariali", "Dhekiajuli"] },
      { name: "Tinsukia", cities: ["Tinsukia", "Margherita", "Sadiya"] },
      { name: "Udalguri", cities: ["Udalguri", "Tangla", "Kalaigaon"] },
    ]
  },
  {
    name: "Bihar",
    districts: [
      { name: "Araria", cities: ["Araria", "Forbesganj", "Raniganj"] },
      { name: "Arwal", cities: ["Arwal", "Kurtha", "Kaler"] },
      { name: "Aurangabad", cities: ["Aurangabad", "Daudnagar", "Madanpur"] },
      { name: "Banka", cities: ["Banka", "Katoria", "Amarpur"] },
      { name: "Begusarai", cities: ["Begusarai", "Bakhri", "Teghra"] },
      { name: "Bhagalpur", cities: ["Bhagalpur", "Naugachhia", "Kahalgaon"] },
      { name: "Bhojpur", cities: ["Arrah", "Jagdishpur", "Piro"] },
      { name: "Buxar", cities: ["Buxar", "Dumraon", "Kesath"] },
      { name: "Darbhanga", cities: ["Darbhanga", "Benipur", "Jale"] },
      { name: "East Champaran", cities: ["Motihari", "Dhaka", "Raxaul"] },
      { name: "Gaya", cities: ["Gaya", "Tekari", "Sherghati"] },
      { name: "Gopalganj", cities: ["Gopalganj", "Barauli", "Kuchaikote"] },
      { name: "Jamui", cities: ["Jamui", "Sikandra", "Jhajha"] },
      { name: "Jehanabad", cities: ["Jehanabad", "Makhdumpur", "Ghosi"] },
      { name: "Kaimur", cities: ["Bhabua", "Mohania", "Ramgarh"] },
      { name: "Katihar", cities: ["Katihar", "Manihari", "Barari"] },
      { name: "Khagaria", cities: ["Khagaria", "Parbatta", "Mansi"] },
      { name: "Kishanganj", cities: ["Kishanganj", "Bahadurganj", "Thakurganj"] },
      { name: "Lakhisarai", cities: ["Lakhisarai", "Halsi", "Surajgarha"] },
      { name: "Madhepura", cities: ["Madhepura", "Udakishanganj", "Murliganj"] },
      { name: "Madhubani", cities: ["Madhubani", "Jainagar", "Benipatti"] },
      { name: "Munger", cities: ["Munger", "Jamalpur", "Tarapur"] },
      { name: "Muzaffarpur", cities: ["Muzaffarpur", "Sitamarhi", "Sheohar"] },
      { name: "Nalanda", cities: ["Bihar Sharif", "Rajgir", "Hilsa"] },
      { name: "Nawada", cities: ["Nawada", "Rajauli", "Warsaliganj"] },
      { name: "Patna", cities: ["Patna", "Danapur", "Barh"] },
      { name: "Purnia", cities: ["Purnia", "Kasba", "Banmankhi"] },
      { name: "Rohtas", cities: ["Sasaram", "Dehri", "Nokha"] },
      { name: "Saharsa", cities: ["Saharsa", "Simri Bakhtiarpur", "Kahara"] },
      { name: "Samastipur", cities: ["Samastipur", "Dalsinghsarai", "Rosera"] },
      { name: "Saran", cities: ["Chhapra", "Marhaura", "Amnour"] },
      { name: "Sheikhpura", cities: ["Sheikhpura", "Barbigha", "Chewara"] },
      { name: "Sheohar", cities: ["Sheohar", "Purnahiya", "Dumri Katsari"] },
      { name: "Sitamarhi", cities: ["Sitamarhi", "Pupri", "Bairgania"] },
      { name: "Siwan", cities: ["Siwan", "Maharajganj", "Mairwa"] },
      { name: "Supaul", cities: ["Supaul", "Birpur", "Nirmali"] },
      { name: "Vaishali", cities: ["Hajipur", "Mahua", "Lalganj"] },
      { name: "West Champaran", cities: ["Bettiah", "Bagaha", "Narkatiaganj"] },
    ]
  },
  {
    name: "Chhattisgarh",
    districts: [
      { name: "Balod", cities: ["Balod", "Gurur", "Dondi"] },
      { name: "Baloda Bazar", cities: ["Baloda Bazar", "Bhatapara", "Palari"] },
      { name: "Balrampur", cities: ["Balrampur", "Rajpur", "Wadrafnagar"] },
      { name: "Bastar", cities: ["Jagdalpur", "Tokapal", "Bakawand"] },
      { name: "Bemetara", cities: ["Bemetara", "Nawagarh", "Saja"] },
      { name: "Bijapur", cities: ["Bijapur", "Bhopalpatnam", "Usoor"] },
      { name: "Bilaspur", cities: ["Bilaspur", "Ratanpur", "Kota"] },
      { name: "Dantewada", cities: ["Dantewada", "Kuakonda", "Katekalyan"] },
      { name: "Dhamtari", cities: ["Dhamtari", "Kurud", "Nagri"] },
      { name: "Durg", cities: ["Durg", "Bhilai", "Patan"] },
      { name: "Gariaband", cities: ["Gariaband", "Fingeshwar", "Deobhog"] },
      { name: "Janjgir-Champa", cities: ["Janjgir", "Champa", "Naila"] },
      { name: "Jashpur", cities: ["Jashpur", "Kunkuri", "Pathalgaon"] },
      { name: "Kabirdham", cities: ["Kawardha", "Pandariya", "Bodla"] },
      { name: "Kanker", cities: ["Kanker", "Bhanupratappur", "Charama"] },
      { name: "Kondagaon", cities: ["Kondagaon", "Makdi", "Pharasgaon"] },
      { name: "Korba", cities: ["Korba", "Katghora", "Pali"] },
      { name: "Koriya", cities: ["Baikunthpur", "Manendragarh", "Bharatpur"] },
      { name: "Mahasamund", cities: ["Mahasamund", "Saraipali", "Basna"] },
      { name: "Mungeli", cities: ["Mungeli", "Lormi", "Patharia"] },
      { name: "Narayanpur", cities: ["Narayanpur", "Orchha"] },
      { name: "Raigarh", cities: ["Raigarh", "Sarangarh", "Dharamjaigarh"] },
      { name: "Raipur", cities: ["Raipur", "Arang", "Tilda"] },
      { name: "Rajnandgaon", cities: ["Rajnandgaon", "Dongargaon", "Chhuria"] },
      { name: "Sukma", cities: ["Sukma", "Konta", "Chintagufa"] },
      { name: "Surajpur", cities: ["Surajpur", "Premnagar", "Odgi"] },
      { name: "Surguja", cities: ["Ambikapur", "Sitapur", "Lakhanpur"] },
    ]
  },
  {
    name: "Delhi",
    districts: [
      { name: "Central Delhi", cities: ["Connaught Place", "Karol Bagh", "Paharganj"] },
      { name: "East Delhi", cities: ["Preet Vihar", "Mayur Vihar", "Laxmi Nagar"] },
      { name: "New Delhi", cities: ["Chanakyapuri", "Parliament Street", "India Gate"] },
      { name: "North Delhi", cities: ["Civil Lines", "Narela", "Model Town"] },
      { name: "North East Delhi", cities: ["Seelampur", "Shahdara", "Nand Nagri"] },
      { name: "North West Delhi", cities: ["Rohini", "Pitampura", "Kanjhawala"] },
      { name: "Shahdara", cities: ["Shahdara", "Vivek Vihar", "Dilshad Garden"] },
      { name: "South Delhi", cities: ["Hauz Khas", "Saket", "Vasant Kunj"] },
      { name: "South East Delhi", cities: ["Defence Colony", "Kalkaji", "Greater Kailash"] },
      { name: "South West Delhi", cities: ["Dwarka", "Najafgarh", "Palam"] },
      { name: "West Delhi", cities: ["Janakpuri", "Rajouri Garden", "Vikaspuri"] },
    ]
  },
  {
    name: "Goa",
    districts: [
      { name: "North Goa", cities: ["Panaji", "Mapusa", "Ponda", "Bicholim", "Pernem", "Bardez"] },
      { name: "South Goa", cities: ["Margao", "Vasco da Gama", "Quepem", "Canacona", "Sanguem", "Salcete"] },
    ]
  },
  {
    name: "Gujarat",
    districts: [
      { name: "Ahmedabad", cities: ["Ahmedabad", "Dholka", "Sanand"] },
      { name: "Amreli", cities: ["Amreli", "Bagasara", "Dhari"] },
      { name: "Anand", cities: ["Anand", "Petlad", "Khambhat"] },
      { name: "Aravalli", cities: ["Modasa", "Dhansura", "Malpur"] },
      { name: "Banaskantha", cities: ["Palanpur", "Deesa", "Danta"] },
      { name: "Bharuch", cities: ["Bharuch", "Ankleshwar", "Jambusar"] },
      { name: "Bhavnagar", cities: ["Bhavnagar", "Mahuva", "Sihor"] },
      { name: "Botad", cities: ["Botad", "Gadhada", "Barvala"] },
      { name: "Chhota Udaipur", cities: ["Chhota Udaipur", "Jetpur Pavi", "Sankheda"] },
      { name: "Dahod", cities: ["Dahod", "Limkheda", "Jhalod"] },
      { name: "Dang", cities: ["Ahwa", "Waghai", "Subir"] },
      { name: "Devbhoomi Dwarka", cities: ["Khambhalia", "Dwarka", "Kalyanpur"] },
      { name: "Gandhinagar", cities: ["Gandhinagar", "Kalol", "Mansa"] },
      { name: "Gir Somnath", cities: ["Veraval", "Una", "Kodinar"] },
      { name: "Jamnagar", cities: ["Jamnagar", "Dhrol", "Kalavad"] },
      { name: "Junagadh", cities: ["Junagadh", "Keshod", "Manavadar"] },
      { name: "Kheda", cities: ["Nadiad", "Kapadvanj", "Matar"] },
      { name: "Kutch", cities: ["Bhuj", "Anjar", "Mandvi"] },
      { name: "Mahisagar", cities: ["Lunawada", "Santrampur", "Kadana"] },
      { name: "Mehsana", cities: ["Mehsana", "Visnagar", "Unjha"] },
      { name: "Morbi", cities: ["Morbi", "Maliya", "Tankara"] },
      { name: "Narmada", cities: ["Rajpipla", "Nandod", "Dediapada"] },
      { name: "Navsari", cities: ["Navsari", "Jalalpore", "Chikhli"] },
      { name: "Panchmahal", cities: ["Godhra", "Halol", "Kalol"] },
      { name: "Patan", cities: ["Patan", "Radhanpur", "Chanasma"] },
      { name: "Porbandar", cities: ["Porbandar", "Ranavav", "Kutiyana"] },
      { name: "Rajkot", cities: ["Rajkot", "Gondal", "Jetpur"] },
      { name: "Sabarkantha", cities: ["Himmatnagar", "Idar", "Prantij"] },
      { name: "Surat", cities: ["Surat", "Bardoli", "Kamrej"] },
      { name: "Surendranagar", cities: ["Surendranagar", "Wadhwan", "Dhrangadhra"] },
      { name: "Tapi", cities: ["Vyara", "Songadh", "Valod"] },
      { name: "Vadodara", cities: ["Vadodara", "Dabhoi", "Padra"] },
      { name: "Valsad", cities: ["Valsad", "Vapi", "Pardi"] },
    ]
  },
  {
    name: "Haryana",
    districts: [
      { name: "Ambala", cities: ["Ambala", "Ambala Cantt", "Naraingarh"] },
      { name: "Bhiwani", cities: ["Bhiwani", "Loharu", "Siwani"] },
      { name: "Charkhi Dadri", cities: ["Charkhi Dadri", "Badhra", "Jhajjar"] },
      { name: "Faridabad", cities: ["Faridabad", "Ballabgarh", "Palwal"] },
      { name: "Fatehabad", cities: ["Fatehabad", "Tohana", "Ratia"] },
      { name: "Gurugram", cities: ["Gurugram", "Sohna", "Pataudi"] },
      { name: "Hisar", cities: ["Hisar", "Hansi", "Barwala"] },
      { name: "Jhajjar", cities: ["Jhajjar", "Bahadurgarh", "Beri"] },
      { name: "Jind", cities: ["Jind", "Narwana", "Safidon"] },
      { name: "Kaithal", cities: ["Kaithal", "Pundri", "Guhla"] },
      { name: "Karnal", cities: ["Karnal", "Gharaunda", "Assandh"] },
      { name: "Kurukshetra", cities: ["Kurukshetra", "Thanesar", "Pehowa"] },
      { name: "Mahendragarh", cities: ["Narnaul", "Mahendragarh", "Ateli"] },
      { name: "Nuh", cities: ["Nuh", "Ferozepur Jhirka", "Punhana"] },
      { name: "Palwal", cities: ["Palwal", "Hathin", "Hodal"] },
      { name: "Panchkula", cities: ["Panchkula", "Kalka", "Pinjore"] },
      { name: "Panipat", cities: ["Panipat", "Samalkha", "Madlauda"] },
      { name: "Rewari", cities: ["Rewari", "Bawal", "Kosli"] },
      { name: "Rohtak", cities: ["Rohtak", "Meham", "Kalanaur"] },
      { name: "Sirsa", cities: ["Sirsa", "Dabwali", "Ellenabad"] },
      { name: "Sonipat", cities: ["Sonipat", "Gohana", "Kharkhoda"] },
      { name: "Yamunanagar", cities: ["Yamunanagar", "Jagadhri", "Chhachhrauli"] },
    ]
  },
  {
    name: "Himachal Pradesh",
    districts: [
      { name: "Bilaspur", cities: ["Bilaspur", "Ghumarwin", "Jhandutta"] },
      { name: "Chamba", cities: ["Chamba", "Dalhousie", "Bharmour"] },
      { name: "Hamirpur", cities: ["Hamirpur", "Nadaun", "Sujanpur"] },
      { name: "Kangra", cities: ["Dharamshala", "Kangra", "Palampur"] },
      { name: "Kinnaur", cities: ["Reckong Peo", "Kalpa", "Nichar"] },
      { name: "Kullu", cities: ["Kullu", "Manali", "Bhuntar"] },
      { name: "Lahaul and Spiti", cities: ["Keylong", "Kaza", "Udaipur"] },
      { name: "Mandi", cities: ["Mandi", "Sundernagar", "Jogindernagar"] },
      { name: "Shimla", cities: ["Shimla", "Solan", "Kasauli"] },
      { name: "Sirmaur", cities: ["Nahan", "Paonta Sahib", "Rajgarh"] },
      { name: "Solan", cities: ["Solan", "Baddi", "Nalagarh"] },
      { name: "Una", cities: ["Una", "Amb", "Bangana"] },
    ]
  },
  {
    name: "Jharkhand",
    districts: [
      { name: "Bokaro", cities: ["Bokaro", "Chas", "Phusro"] },
      { name: "Chatra", cities: ["Chatra", "Simaria", "Hunterganj"] },
      { name: "Deoghar", cities: ["Deoghar", "Madhupur", "Jasidih"] },
      { name: "Dhanbad", cities: ["Dhanbad", "Jharia", "Sindri"] },
      { name: "Dumka", cities: ["Dumka", "Shikaripara", "Jama"] },
      { name: "East Singhbhum", cities: ["Jamshedpur", "Ghatsila", "Chaibasa"] },
      { name: "Garhwa", cities: ["Garhwa", "Nagar Untari", "Bishrampur"] },
      { name: "Giridih", cities: ["Giridih", "Dumri", "Bengabad"] },
      { name: "Godda", cities: ["Godda", "Mahagama", "Poreyahat"] },
      { name: "Gumla", cities: ["Gumla", "Basia", "Sisai"] },
      { name: "Hazaribagh", cities: ["Hazaribagh", "Barhi", "Chatra"] },
      { name: "Jamtara", cities: ["Jamtara", "Narayanpur", "Kundhit"] },
      { name: "Khunti", cities: ["Khunti", "Murhu", "Torpa"] },
      { name: "Kodarma", cities: ["Kodarma", "Jhumri Telaiya", "Chandwara"] },
      { name: "Latehar", cities: ["Latehar", "Manika", "Balumath"] },
      { name: "Lohardaga", cities: ["Lohardaga", "Senha", "Kuru"] },
      { name: "Pakur", cities: ["Pakur", "Maheshpur", "Pakuria"] },
      { name: "Palamu", cities: ["Daltonganj", "Medininagar", "Panki"] },
      { name: "Ramgarh", cities: ["Ramgarh", "Mandu", "Gola"] },
      { name: "Ranchi", cities: ["Ranchi", "Bundu", "Khunti"] },
      { name: "Sahebganj", cities: ["Sahebganj", "Rajmahal", "Barharwa"] },
      { name: "Seraikela Kharsawan", cities: ["Seraikela", "Kharsawan", "Chandil"] },
      { name: "Simdega", cities: ["Simdega", "Bolba", "Kolebira"] },
      { name: "West Singhbhum", cities: ["Chaibasa", "Chakradharpur", "Manoharpur"] },
    ]
  },
  {
    name: "Karnataka",
    districts: [
      { name: "Bagalkot", cities: ["Bagalkot", "Jamkhandi", "Mudhol"] },
      { name: "Ballari", cities: ["Ballari", "Hospet", "Sandur"] },
      { name: "Belagavi", cities: ["Belagavi", "Bailhongal", "Chikkodi"] },
      { name: "Bengaluru Rural", cities: ["Devanahalli", "Doddaballapura", "Hosakote"] },
      { name: "Bengaluru Urban", cities: ["Bangalore", "Anekal", "Bengaluru North"] },
      { name: "Bidar", cities: ["Bidar", "Bhalki", "Basavakalyan"] },
      { name: "Chamarajanagar", cities: ["Chamarajanagar", "Gundlupet", "Kollegala"] },
      { name: "Chikkaballapur", cities: ["Chikkaballapur", "Bagepalli", "Chintamani"] },
      { name: "Chikkamagaluru", cities: ["Chikkamagaluru", "Kadur", "Tarikere"] },
      { name: "Chitradurga", cities: ["Chitradurga", "Challakere", "Holalkere"] },
      { name: "Dakshina Kannada", cities: ["Mangaluru", "Bantwal", "Puttur"] },
      { name: "Davanagere", cities: ["Davanagere", "Harihara", "Honnali"] },
      { name: "Dharwad", cities: ["Dharwad", "Hubli", "Kalghatgi"] },
      { name: "Gadag", cities: ["Gadag", "Mundargi", "Nargund"] },
      { name: "Hassan", cities: ["Hassan", "Arsikere", "Belur"] },
      { name: "Haveri", cities: ["Haveri", "Byadgi", "Hanagal"] },
      { name: "Kalaburagi", cities: ["Kalaburagi", "Afzalpur", "Aland"] },
      { name: "Kodagu", cities: ["Madikeri", "Virajpet", "Somwarpet"] },
      { name: "Kolar", cities: ["Kolar", "Malur", "Bangarpet"] },
      { name: "Koppal", cities: ["Koppal", "Gangavathi", "Kushtagi"] },
      { name: "Mandya", cities: ["Mandya", "Maddur", "Malavalli"] },
      { name: "Mysuru", cities: ["Mysuru", "Nanjangud", "T. Narasipura"] },
      { name: "Raichur", cities: ["Raichur", "Sindhnur", "Manvi"] },
      { name: "Ramanagara", cities: ["Ramanagara", "Channapatna", "Magadi"] },
      { name: "Shivamogga", cities: ["Shivamogga", "Bhadravati", "Sagar"] },
      { name: "Tumakuru", cities: ["Tumakuru", "Tiptur", "Turuvekere"] },
      { name: "Udupi", cities: ["Udupi", "Manipal", "Kundapura"] },
      { name: "Uttara Kannada", cities: ["Karwar", "Sirsi", "Kumta"] },
      { name: "Vijayapura", cities: ["Vijayapura", "Indi", "Sindgi"] },
      { name: "Yadgir", cities: ["Yadgir", "Shahapur", "Shorapur"] },
    ]
  },
  {
    name: "Kerala",
    districts: [
      { name: "Alappuzha", cities: ["Alappuzha", "Cherthala", "Kayamkulam"] },
      { name: "Ernakulam", cities: ["Kochi", "Aluva", "Perumbavoor"] },
      { name: "Idukki", cities: ["Thodupuzha", "Munnar", "Kattappana"] },
      { name: "Kannur", cities: ["Kannur", "Thalassery", "Payyanur"] },
      { name: "Kasaragod", cities: ["Kasaragod", "Kanhangad", "Nileshwar"] },
      { name: "Kollam", cities: ["Kollam", "Punalur", "Karunagappally"] },
      { name: "Kottayam", cities: ["Kottayam", "Changanassery", "Pala"] },
      { name: "Kozhikode", cities: ["Kozhikode", "Vadakara", "Koyilandy"] },
      { name: "Malappuram", cities: ["Malappuram", "Manjeri", "Tirur"] },
      { name: "Palakkad", cities: ["Palakkad", "Ottappalam", "Mannarkkad"] },
      { name: "Pathanamthitta", cities: ["Pathanamthitta", "Adoor", "Thiruvalla"] },
      { name: "Thiruvananthapuram", cities: ["Thiruvananthapuram", "Neyyattinkara", "Varkala"] },
      { name: "Thrissur", cities: ["Thrissur", "Chalakudy", "Kodungallur"] },
      { name: "Wayanad", cities: ["Kalpetta", "Sulthan Bathery", "Mananthavady"] },
    ]
  },
  {
    name: "Madhya Pradesh",
    districts: [
      { name: "Agar Malwa", cities: ["Agar", "Susner", "Nalkheda"] },
      { name: "Alirajpur", cities: ["Alirajpur", "Jobat", "Bhabra"] },
      { name: "Anuppur", cities: ["Anuppur", "Jaithari", "Kotma"] },
      { name: "Ashoknagar", cities: ["Ashoknagar", "Chanderi", "Mungaoli"] },
      { name: "Balaghat", cities: ["Balaghat", "Waraseoni", "Lanji"] },
      { name: "Barwani", cities: ["Barwani", "Sendhwa", "Pansemal"] },
      { name: "Betul", cities: ["Betul", "Multai", "Bhainsdehi"] },
      { name: "Bhind", cities: ["Bhind", "Lahar", "Mihona"] },
      { name: "Bhopal", cities: ["Bhopal", "Berasia", "Huzur"] },
      { name: "Burhanpur", cities: ["Burhanpur", "Shahpur", "Khaknar"] },
      { name: "Chhatarpur", cities: ["Chhatarpur", "Nowgong", "Bijawar"] },
      { name: "Chhindwara", cities: ["Chhindwara", "Parasia", "Tamia"] },
      { name: "Damoh", cities: ["Damoh", "Hatta", "Patharia"] },
      { name: "Datia", cities: ["Datia", "Seondha", "Bhander"] },
      { name: "Dewas", cities: ["Dewas", "Khategaon", "Bagli"] },
      { name: "Dhar", cities: ["Dhar", "Manawar", "Sardarpur"] },
      { name: "Dindori", cities: ["Dindori", "Shahpura", "Samnapur"] },
      { name: "Guna", cities: ["Guna", "Raghogarh", "Aron"] },
      { name: "Gwalior", cities: ["Gwalior", "Dabra", "Bhitarwar"] },
      { name: "Harda", cities: ["Harda", "Khirkiya", "Timarni"] },
      { name: "Hoshangabad", cities: ["Hoshangabad", "Itarsi", "Sohagpur"] },
      { name: "Indore", cities: ["Indore", "Mhow", "Sanwer"] },
      { name: "Jabalpur", cities: ["Jabalpur", "Sihora", "Kundam"] },
      { name: "Jhabua", cities: ["Jhabua", "Petlawad", "Ranapur"] },
      { name: "Katni", cities: ["Katni", "Vijayraghogarh", "Bahoriband"] },
      { name: "Khandwa", cities: ["Khandwa", "Pandhana", "Khalwa"] },
      { name: "Khargone", cities: ["Khargone", "Maheshwar", "Barwaha"] },
      { name: "Mandla", cities: ["Mandla", "Nainpur", "Bichhiya"] },
      { name: "Mandsaur", cities: ["Mandsaur", "Sitamau", "Garoth"] },
      { name: "Morena", cities: ["Morena", "Porsa", "Joura"] },
      { name: "Narsinghpur", cities: ["Narsinghpur", "Gadarwara", "Kareli"] },
      { name: "Neemuch", cities: ["Neemuch", "Manasa", "Jawad"] },
      { name: "Niwari", cities: ["Niwari", "Prithvipur", "Orchha"] },
      { name: "Panna", cities: ["Panna", "Pawai", "Ajaigarh"] },
      { name: "Raisen", cities: ["Raisen", "Bareli", "Begamganj"] },
      { name: "Rajgarh", cities: ["Rajgarh", "Sarangpur", "Biaora"] },
      { name: "Ratlam", cities: ["Ratlam", "Sailana", "Jaora"] },
      { name: "Rewa", cities: ["Rewa", "Sirmour", "Teonthar"] },
      { name: "Sagar", cities: ["Sagar", "Rehli", "Khurai"] },
      { name: "Satna", cities: ["Satna", "Maihar", "Nagod"] },
      { name: "Sehore", cities: ["Sehore", "Ashta", "Nasrullaganj"] },
      { name: "Seoni", cities: ["Seoni", "Lakhnadon", "Barghat"] },
      { name: "Shahdol", cities: ["Shahdol", "Beohari", "Jaisinghnagar"] },
      { name: "Shajapur", cities: ["Shajapur", "Kalapipal", "Moman Badodiya"] },
      { name: "Sheopur", cities: ["Sheopur", "Vijaypur", "Karahal"] },
      { name: "Shivpuri", cities: ["Shivpuri", "Kolaras", "Pichhore"] },
      { name: "Sidhi", cities: ["Sidhi", "Singrauli", "Churhat"] },
      { name: "Singrauli", cities: ["Singrauli", "Waidhan", "Chitrangi"] },
      { name: "Tikamgarh", cities: ["Tikamgarh", "Baldeogarh", "Niwari"] },
      { name: "Ujjain", cities: ["Ujjain", "Nagda", "Mahidpur"] },
      { name: "Umaria", cities: ["Umaria", "Manpur", "Pali"] },
      { name: "Vidisha", cities: ["Vidisha", "Sironj", "Kurwai"] },
    ]
  },
  {
    name: "Maharashtra",
    districts: [
      { name: "Ahmednagar", cities: ["Ahmednagar", "Shrirampur", "Sangamner"] },
      { name: "Akola", cities: ["Akola", "Telhara", "Barshitakli"] },
      { name: "Amravati", cities: ["Amravati", "Achalpur", "Dharni"] },
      { name: "Aurangabad", cities: ["Aurangabad", "Vaijapur", "Khultabad"] },
      { name: "Beed", cities: ["Beed", "Parli", "Patoda"] },
      { name: "Bhandara", cities: ["Bhandara", "Tumsar", "Pauni"] },
      { name: "Buldhana", cities: ["Buldhana", "Khamgaon", "Malkapur"] },
      { name: "Chandrapur", cities: ["Chandrapur", "Ballarpur", "Warora"] },
      { name: "Dhule", cities: ["Dhule", "Sakri", "Sindkheda"] },
      { name: "Gadchiroli", cities: ["Gadchiroli", "Aheri", "Dhanora"] },
      { name: "Gondia", cities: ["Gondia", "Tirora", "Arjuni Morgaon"] },
      { name: "Hingoli", cities: ["Hingoli", "Kalamnuri", "Basmath"] },
      { name: "Jalgaon", cities: ["Jalgaon", "Bhusawal", "Chopda"] },
      { name: "Jalna", cities: ["Jalna", "Partur", "Ambad"] },
      { name: "Kolhapur", cities: ["Kolhapur", "Ichalkaranji", "Kagal"] },
      { name: "Latur", cities: ["Latur", "Nilanga", "Udgir"] },
      { name: "Mumbai City", cities: ["Mumbai", "Colaba", "Malabar Hill"] },
      { name: "Mumbai Suburban", cities: ["Andheri", "Borivali", "Kurla"] },
      { name: "Nagpur", cities: ["Nagpur", "Kamptee", "Ramtek"] },
      { name: "Nanded", cities: ["Nanded", "Kinwat", "Mukhed"] },
      { name: "Nandurbar", cities: ["Nandurbar", "Shahada", "Taloda"] },
      { name: "Nashik", cities: ["Nashik", "Malegaon", "Sinnar"] },
      { name: "Osmanabad", cities: ["Osmanabad", "Tuljapur", "Paranda"] },
      { name: "Palghar", cities: ["Palghar", "Vasai", "Dahanu"] },
      { name: "Parbhani", cities: ["Parbhani", "Purna", "Gangakhed"] },
      { name: "Pune", cities: ["Pune", "Pimpri-Chinchwad", "Baramati"] },
      { name: "Raigad", cities: ["Alibag", "Panvel", "Khopoli"] },
      { name: "Ratnagiri", cities: ["Ratnagiri", "Chiplun", "Dapoli"] },
      { name: "Sangli", cities: ["Sangli", "Miraj", "Tasgaon"] },
      { name: "Satara", cities: ["Satara", "Karad", "Wai"] },
      { name: "Sindhudurg", cities: ["Kudal", "Malvan", "Sawantwadi"] },
      { name: "Solapur", cities: ["Solapur", "Barshi", "Pandharpur"] },
      { name: "Thane", cities: ["Thane", "Kalyan", "Bhiwandi"] },
      { name: "Wardha", cities: ["Wardha", "Hinganghat", "Arvi"] },
      { name: "Washim", cities: ["Washim", "Karanja", "Risod"] },
      { name: "Yavatmal", cities: ["Yavatmal", "Pusad", "Digras"] },
    ]
  },
  {
    name: "Manipur",
    districts: [
      { name: "Bishnupur", cities: ["Bishnupur", "Moirang", "Nambol"] },
      { name: "Chandel", cities: ["Chandel", "Chakpikarong", "Tengnoupal"] },
      { name: "Churachandpur", cities: ["Churachandpur", "Singngat", "Henglep"] },
      { name: "Imphal East", cities: ["Porompat", "Jiribam", "Sekmai"] },
      { name: "Imphal West", cities: ["Imphal", "Lamphelpat", "Wangoi"] },
      { name: "Jiribam", cities: ["Jiribam", "Borobekra", "Jirighat"] },
      { name: "Kakching", cities: ["Kakching", "Waikhong", "Sugnu"] },
      { name: "Kamjong", cities: ["Kamjong", "Phungyar", "Sahamphung"] },
      { name: "Kangpokpi", cities: ["Kangpokpi", "Saitu", "Saikul"] },
      { name: "Noney", cities: ["Noney", "Longmai", "Haochong"] },
      { name: "Pherzawl", cities: ["Pherzawl", "Vangai", "T. Khullen"] },
      { name: "Senapati", cities: ["Senapati", "Mao", "Paomata"] },
      { name: "Tamenglong", cities: ["Tamenglong", "Nungba", "Tousem"] },
      { name: "Tengnoupal", cities: ["Tengnoupal", "Moreh", "Machi"] },
      { name: "Thoubal", cities: ["Thoubal", "Lilong", "Yairipok"] },
      { name: "Ukhrul", cities: ["Ukhrul", "Lungchong Maiphei", "Chingai"] },
    ]
  },
  {
    name: "Meghalaya",
    districts: [
      { name: "East Garo Hills", cities: ["Williamnagar", "Samanda", "Rongjeng"] },
      { name: "East Jaintia Hills", cities: ["Khliehriat", "Saipung", "Laskein"] },
      { name: "East Khasi Hills", cities: ["Shillong", "Pynursla", "Mylliem"] },
      { name: "North Garo Hills", cities: ["Resubelpara", "Bajengdoba", "Kharkutta"] },
      { name: "Ri Bhoi", cities: ["Nongpoh", "Umsning", "Jirang"] },
      { name: "South Garo Hills", cities: ["Baghmara", "Gasuapara", "Chokpot"] },
      { name: "South West Garo Hills", cities: ["Ampati", "Mahendraganj", "Betasing"] },
      { name: "South West Khasi Hills", cities: ["Mawkyrwat", "Ranikor", "Riangdo"] },
      { name: "West Garo Hills", cities: ["Tura", "Dalu", "Tikrikilla"] },
      { name: "West Jaintia Hills", cities: ["Jowai", "Thadlaskein", "Amlarem"] },
      { name: "West Khasi Hills", cities: ["Nongstoin", "Mairang", "Mawshynrut"] },
    ]
  },
  {
    name: "Mizoram",
    districts: [
      { name: "Aizawl", cities: ["Aizawl", "Darlawn", "Thingsulthliah"] },
      { name: "Champhai", cities: ["Champhai", "Khawzawl", "Ngopa"] },
      { name: "Hnahthial", cities: ["Hnahthial", "Lungsen", "Tuipang"] },
      { name: "Khawzawl", cities: ["Khawzawl", "Buarpui", "N. Vanlaiphai"] },
      { name: "Kolasib", cities: ["Kolasib", "Vairengte", "Thingdawl"] },
      { name: "Lawngtlai", cities: ["Lawngtlai", "Chawngte", "Sangau"] },
      { name: "Lunglei", cities: ["Lunglei", "Hnahthial", "Tlabung"] },
      { name: "Mamit", cities: ["Mamit", "Zawlnuam", "Reiek"] },
      { name: "Saiha", cities: ["Saiha", "Tuipang", "Lawngtlai"] },
      { name: "Saitual", cities: ["Saitual", "Phullen", "Keifang"] },
      { name: "Serchhip", cities: ["Serchhip", "Thenzawl", "N. Kawnpui"] },
    ]
  },
  {
    name: "Nagaland",
    districts: [
      { name: "Dimapur", cities: ["Dimapur", "Chumukedima", "Dhansiripar"] },
      { name: "Kiphire", cities: ["Kiphire", "Pungro", "Sitimi"] },
      { name: "Kohima", cities: ["Kohima", "Chakabama", "Tseminyu"] },
      { name: "Longleng", cities: ["Longleng", "Tamlu", "Sakshi"] },
      { name: "Mokokchung", cities: ["Mokokchung", "Mangkolemba", "Tuli"] },
      { name: "Mon", cities: ["Mon", "Tizit", "Aboi"] },
      { name: "Peren", cities: ["Peren", "Jalukie", "Tening"] },
      { name: "Phek", cities: ["Phek", "Pfutsero", "Chozuba"] },
      { name: "Tuensang", cities: ["Tuensang", "Noklak", "Shamator"] },
      { name: "Wokha", cities: ["Wokha", "Bhandari", "Chukitong"] },
      { name: "Zunheboto", cities: ["Zunheboto", "Satakha", "Aghunato"] },
    ]
  },
  {
    name: "Odisha",
    districts: [
      { name: "Angul", cities: ["Angul", "Talcher", "Athmallik"] },
      { name: "Balangir", cities: ["Balangir", "Titlagarh", "Patnagarh"] },
      { name: "Balasore", cities: ["Balasore", "Bhadrak", "Jaleswar"] },
      { name: "Bargarh", cities: ["Bargarh", "Padampur", "Bijepur"] },
      { name: "Bhadrak", cities: ["Bhadrak", "Chandbali", "Dhamnagar"] },
      { name: "Boudh", cities: ["Boudh", "Kantamal", "Harbhanga"] },
      { name: "Cuttack", cities: ["Cuttack", "Banki", "Athagarh"] },
      { name: "Deogarh", cities: ["Deogarh", "Reamal", "Barkote"] },
      { name: "Dhenkanal", cities: ["Dhenkanal", "Kamakhyanagar", "Hindol"] },
      { name: "Gajapati", cities: ["Paralakhemundi", "Kashinagar", "Rayagada"] },
      { name: "Ganjam", cities: ["Berhampur", "Chatrapur", "Gopalpur"] },
      { name: "Jagatsinghpur", cities: ["Jagatsinghpur", "Paradeep", "Tirtol"] },
      { name: "Jajpur", cities: ["Jajpur", "Vyasanagar", "Korai"] },
      { name: "Jharsuguda", cities: ["Jharsuguda", "Brajrajnagar", "Belpahar"] },
      { name: "Kalahandi", cities: ["Bhawanipatna", "Dharmagarh", "Junagarh"] },
      { name: "Kandhamal", cities: ["Phulbani", "Baliguda", "G. Udayagiri"] },
      { name: "Kendrapara", cities: ["Kendrapara", "Pattamundai", "Aul"] },
      { name: "Kendujhar", cities: ["Kendujhar", "Barbil", "Anandapur"] },
      { name: "Khordha", cities: ["Bhubaneswar", "Khordha", "Jatani"] },
      { name: "Koraput", cities: ["Koraput", "Jeypore", "Sunabeda"] },
      { name: "Malkangiri", cities: ["Malkangiri", "Mathili", "Kudumuluguma"] },
      { name: "Mayurbhanj", cities: ["Baripada", "Rairangpur", "Karanjia"] },
      { name: "Nabarangpur", cities: ["Nabarangpur", "Umerkote", "Papadahandi"] },
      { name: "Nayagarh", cities: ["Nayagarh", "Odagaon", "Dasapalla"] },
      { name: "Nuapada", cities: ["Nuapada", "Khariar", "Sinapali"] },
      { name: "Puri", cities: ["Puri", "Konark", "Pipili"] },
      { name: "Rayagada", cities: ["Rayagada", "Gunupur", "Gudari"] },
      { name: "Sambalpur", cities: ["Sambalpur", "Burla", "Rairakhol"] },
      { name: "Subarnapur", cities: ["Sonepur", "Birmaharajpur", "Tarbha"] },
      { name: "Sundargarh", cities: ["Rourkela", "Sundargarh", "Rajgangpur"] },
    ]
  },
  {
    name: "Punjab",
    districts: [
      { name: "Amritsar", cities: ["Amritsar", "Ajnala", "Majitha"] },
      { name: "Barnala", cities: ["Barnala", "Tapa", "Handiaya"] },
      { name: "Bathinda", cities: ["Bathinda", "Talwandi Sabo", "Rampura Phul"] },
      { name: "Faridkot", cities: ["Faridkot", "Jaitu", "Kotkapura"] },
      { name: "Fatehgarh Sahib", cities: ["Fatehgarh Sahib", "Bassi Pathana", "Sirhind"] },
      { name: "Fazilka", cities: ["Fazilka", "Abohar", "Jalalabad"] },
      { name: "Ferozepur", cities: ["Ferozepur", "Zira", "Fazilka"] },
      { name: "Gurdaspur", cities: ["Gurdaspur", "Batala", "Pathankot"] },
      { name: "Hoshiarpur", cities: ["Hoshiarpur", "Dasuya", "Mukerian"] },
      { name: "Jalandhar", cities: ["Jalandhar", "Phillaur", "Nakodar"] },
      { name: "Kapurthala", cities: ["Kapurthala", "Phagwara", "Sultanpur Lodhi"] },
      { name: "Ludhiana", cities: ["Ludhiana", "Khanna", "Samrala"] },
      { name: "Mansa", cities: ["Mansa", "Budhlada", "Sardulgarh"] },
      { name: "Moga", cities: ["Moga", "Baghapurana", "Nihal Singh Wala"] },
      { name: "Muktsar", cities: ["Muktsar", "Malout", "Gidderbaha"] },
      { name: "Pathankot", cities: ["Pathankot", "Sujanpur", "Bamial"] },
      { name: "Patiala", cities: ["Patiala", "Rajpura", "Samana"] },
      { name: "Rupnagar", cities: ["Rupnagar", "Anandpur Sahib", "Nangal"] },
      { name: "Sangrur", cities: ["Sangrur", "Sunam", "Malerkotla"] },
      { name: "SAS Nagar", cities: ["Mohali", "Dera Bassi", "Kurali"] },
      { name: "Shaheed Bhagat Singh Nagar", cities: ["Nawanshahr", "Balachaur", "Banga"] },
      { name: "Tarn Taran", cities: ["Tarn Taran", "Patti", "Khadoor Sahib"] },
    ]
  },
  {
    name: "Rajasthan",
    districts: [
      { name: "Ajmer", cities: ["Ajmer", "Pushkar", "Beawar"] },
      { name: "Alwar", cities: ["Alwar", "Behror", "Tijara"] },
      { name: "Banswara", cities: ["Banswara", "Ghatol", "Kushalgarh"] },
      { name: "Baran", cities: ["Baran", "Atru", "Chhipabarod"] },
      { name: "Barmer", cities: ["Barmer", "Balotra", "Sheo"] },
      { name: "Bharatpur", cities: ["Bharatpur", "Deeg", "Kumher"] },
      { name: "Bhilwara", cities: ["Bhilwara", "Shahpura", "Mandal"] },
      { name: "Bikaner", cities: ["Bikaner", "Nokha", "Kolayat"] },
      { name: "Bundi", cities: ["Bundi", "Keshoraipatan", "Nainwa"] },
      { name: "Chittorgarh", cities: ["Chittorgarh", "Nimbahera", "Kapasan"] },
      { name: "Churu", cities: ["Churu", "Sardarshahar", "Ratangarh"] },
      { name: "Dausa", cities: ["Dausa", "Lalsot", "Baswa"] },
      { name: "Dholpur", cities: ["Dholpur", "Bari", "Rajakhera"] },
      { name: "Dungarpur", cities: ["Dungarpur", "Aspur", "Sagwara"] },
      { name: "Hanumangarh", cities: ["Hanumangarh", "Pilibanga", "Nohar"] },
      { name: "Jaipur", cities: ["Jaipur", "Sanganer", "Chomu"] },
      { name: "Jaisalmer", cities: ["Jaisalmer", "Pokaran", "Fatehgarh"] },
      { name: "Jalore", cities: ["Jalore", "Bhinmal", "Sanchore"] },
      { name: "Jhalawar", cities: ["Jhalawar", "Jhalrapatan", "Khanpur"] },
      { name: "Jhunjhunu", cities: ["Jhunjhunu", "Chirawa", "Nawalgarh"] },
      { name: "Jodhpur", cities: ["Jodhpur", "Bilara", "Phalodi"] },
      { name: "Karauli", cities: ["Karauli", "Hindaun", "Todabhim"] },
      { name: "Kota", cities: ["Kota", "Ramganj Mandi", "Sangod"] },
      { name: "Nagaur", cities: ["Nagaur", "Merta", "Didwana"] },
      { name: "Pali", cities: ["Pali", "Sojat", "Jaitaran"] },
      { name: "Pratapgarh", cities: ["Pratapgarh", "Arnod", "Chhoti Sadri"] },
      { name: "Rajsamand", cities: ["Rajsamand", "Kumbhalgarh", "Nathdwara"] },
      { name: "Sawai Madhopur", cities: ["Sawai Madhopur", "Gangapur", "Bonli"] },
      { name: "Sikar", cities: ["Sikar", "Fatehpur", "Danta Ramgarh"] },
      { name: "Sirohi", cities: ["Sirohi", "Mount Abu", "Pindwara"] },
      { name: "Sri Ganganagar", cities: ["Sri Ganganagar", "Suratgarh", "Anupgarh"] },
      { name: "Tonk", cities: ["Tonk", "Newai", "Malpura"] },
      { name: "Udaipur", cities: ["Udaipur", "Mavli", "Salumbar"] },
    ]
  },
  {
    name: "Sikkim",
    districts: [
      { name: "East Sikkim", cities: ["Gangtok", "Pakyong", "Rongli"] },
      { name: "North Sikkim", cities: ["Mangan", "Chungthang", "Lachung"] },
      { name: "South Sikkim", cities: ["Namchi", "Jorethang", "Ravangla"] },
      { name: "West Sikkim", cities: ["Geyzing", "Pelling", "Yuksom"] },
    ]
  },
  {
    name: "Tamil Nadu",
    districts: [
      { name: "Ariyalur", cities: ["Ariyalur", "Sendurai", "Udayarpalayam"] },
      { name: "Chengalpattu", cities: ["Chengalpattu", "Madurantakam", "Tambaram"] },
      { name: "Chennai", cities: ["Chennai", "Adyar", "Mylapore"] },
      { name: "Coimbatore", cities: ["Coimbatore", "Pollachi", "Mettupalayam"] },
      { name: "Cuddalore", cities: ["Cuddalore", "Chidambaram", "Neyveli"] },
      { name: "Dharmapuri", cities: ["Dharmapuri", "Harur", "Palacode"] },
      { name: "Dindigul", cities: ["Dindigul", "Kodaikanal", "Palani"] },
      { name: "Erode", cities: ["Erode", "Gobichettipalayam", "Bhavani"] },
      { name: "Kallakurichi", cities: ["Kallakurichi", "Sankarapuram", "Ulundurpet"] },
      { name: "Kanchipuram", cities: ["Kanchipuram", "Sriperumbudur", "Uthiramerur"] },
      { name: "Kanyakumari", cities: ["Nagercoil", "Padmanabhapuram", "Colachel"] },
      { name: "Karur", cities: ["Karur", "Kulithalai", "Aravakurichi"] },
      { name: "Krishnagiri", cities: ["Krishnagiri", "Hosur", "Denkanikottai"] },
      { name: "Madurai", cities: ["Madurai", "Usilampatti", "Melur"] },
      { name: "Nagapattinam", cities: ["Nagapattinam", "Mayiladuthurai", "Sirkali"] },
      { name: "Namakkal", cities: ["Namakkal", "Tiruchengode", "Rasipuram"] },
      { name: "Nilgiris", cities: ["Ooty", "Coonoor", "Gudalur"] },
      { name: "Perambalur", cities: ["Perambalur", "Veppanthattai", "Alathur"] },
      { name: "Pudukkottai", cities: ["Pudukkottai", "Aranthangi", "Iluppur"] },
      { name: "Ramanathapuram", cities: ["Ramanathapuram", "Rameswaram", "Paramakudi"] },
      { name: "Ranipet", cities: ["Ranipet", "Walajah", "Arcot"] },
      { name: "Salem", cities: ["Salem", "Attur", "Mettur"] },
      { name: "Sivaganga", cities: ["Sivaganga", "Karaikudi", "Devakottai"] },
      { name: "Tenkasi", cities: ["Tenkasi", "Sankarankovil", "Shencottai"] },
      { name: "Thanjavur", cities: ["Thanjavur", "Kumbakonam", "Pattukkottai"] },
      { name: "Theni", cities: ["Theni", "Periyakulam", "Bodinayakanur"] },
      { name: "Thoothukudi", cities: ["Thoothukudi", "Kovilpatti", "Tiruchendur"] },
      { name: "Tiruchirappalli", cities: ["Tiruchirappalli", "Srirangam", "Lalgudi"] },
      { name: "Tirunelveli", cities: ["Tirunelveli", "Palayamkottai", "Ambasamudram"] },
      { name: "Tirupathur", cities: ["Tirupathur", "Ambur", "Natrampalli"] },
      { name: "Tiruppur", cities: ["Tiruppur", "Avinashi", "Dharapuram"] },
      { name: "Tiruvallur", cities: ["Tiruvallur", "Poonamallee", "Gummidipoondi"] },
      { name: "Tiruvannamalai", cities: ["Tiruvannamalai", "Arani", "Cheyyar"] },
      { name: "Tiruvarur", cities: ["Tiruvarur", "Mannargudi", "Nannilam"] },
      { name: "Vellore", cities: ["Vellore", "Katpadi", "Gudiyatham"] },
      { name: "Viluppuram", cities: ["Viluppuram", "Tindivanam", "Gingee"] },
      { name: "Virudhunagar", cities: ["Virudhunagar", "Sivakasi", "Srivilliputhur"] },
    ]
  },
  {
    name: "Telangana",
    districts: [
      { name: "Adilabad", cities: ["Adilabad", "Mancherial", "Bellampalli"] },
      { name: "Bhadradri Kothagudem", cities: ["Kothagudem", "Palvancha", "Manuguru"] },
      { name: "Hyderabad", cities: ["Hyderabad", "Secunderabad", "Kukatpally"] },
      { name: "Jagtial", cities: ["Jagtial", "Metpally", "Korutla"] },
      { name: "Jangaon", cities: ["Jangaon", "Ghanpur", "Kodakandla"] },
      { name: "Jayashankar Bhupalpally", cities: ["Bhupalpally", "Mulug", "Regonda"] },
      { name: "Jogulamba Gadwal", cities: ["Gadwal", "Wanaparthy", "Ieeja"] },
      { name: "Kamareddy", cities: ["Kamareddy", "Banswada", "Yellareddy"] },
      { name: "Karimnagar", cities: ["Karimnagar", "Huzurabad", "Choppadandi"] },
      { name: "Khammam", cities: ["Khammam", "Yellandu", "Sathupalli"] },
      { name: "Komaram Bheem", cities: ["Asifabad", "Sirpur", "Kagaznagar"] },
      { name: "Mahabubabad", cities: ["Mahabubabad", "Dornakal", "Garla"] },
      { name: "Mahbubnagar", cities: ["Mahbubnagar", "Jadcherla", "Narayanpet"] },
      { name: "Mancherial", cities: ["Mancherial", "Bellampalli", "Mandamarri"] },
      { name: "Medak", cities: ["Medak", "Sangareddy", "Narsapur"] },
      { name: "Medchal-Malkajgiri", cities: ["Medchal", "Kompally", "Shamirpet"] },
      { name: "Nagarkurnool", cities: ["Nagarkurnool", "Achampet", "Kalwakurthy"] },
      { name: "Nalgonda", cities: ["Nalgonda", "Miryalaguda", "Suryapet"] },
      { name: "Nirmal", cities: ["Nirmal", "Khanapur", "Mudhole"] },
      { name: "Nizamabad", cities: ["Nizamabad", "Bodhan", "Armoor"] },
      { name: "Peddapalli", cities: ["Peddapalli", "Ramagundam", "Manthani"] },
      { name: "Rajanna Sircilla", cities: ["Sircilla", "Vemulawada", "Gambhiraopet"] },
      { name: "Rangareddy", cities: ["LB Nagar", "Chevella", "Vikarabad"] },
      { name: "Sangareddy", cities: ["Sangareddy", "Zaheerabad", "Narayankhed"] },
      { name: "Siddipet", cities: ["Siddipet", "Gajwel", "Dubbak"] },
      { name: "Suryapet", cities: ["Suryapet", "Kodad", "Huzurnagar"] },
      { name: "Vikarabad", cities: ["Vikarabad", "Tandur", "Kodangal"] },
      { name: "Wanaparthy", cities: ["Wanaparthy", "Pebbair", "Gopalpet"] },
      { name: "Warangal Rural", cities: ["Warangal", "Cherial", "Narsampet"] },
      { name: "Warangal Urban", cities: ["Warangal", "Hanamkonda", "Kazipet"] },
      { name: "Yadadri Bhuvanagiri", cities: ["Bhongir", "Yadagirigutta", "Ramannapet"] },
    ]
  },
  {
    name: "Tripura",
    districts: [
      { name: "Dhalai", cities: ["Ambassa", "Kamalpur", "Salema"] },
      { name: "Gomati", cities: ["Udaipur", "Amarpur", "Karbook"] },
      { name: "Khowai", cities: ["Khowai", "Teliamura", "Kalyanpur"] },
      { name: "North Tripura", cities: ["Dharmanagar", "Kanchanpur", "Panisagar"] },
      { name: "Sepahijala", cities: ["Bishramganj", "Sonamura", "Melaghar"] },
      { name: "South Tripura", cities: ["Belonia", "Santirbazar", "Sabroom"] },
      { name: "Unakoti", cities: ["Kailashahar", "Kumarghat", "Pecharthal"] },
      { name: "West Tripura", cities: ["Agartala", "Mohanpur", "Jirania"] },
    ]
  },
  {
    name: "Uttar Pradesh",
    districts: [
      { name: "Agra", cities: ["Agra", "Fatehabad", "Kheragarh"] },
      { name: "Aligarh", cities: ["Aligarh", "Khair", "Iglas"] },
      { name: "Ambedkar Nagar", cities: ["Akbarpur", "Tanda", "Jalalpur"] },
      { name: "Amethi", cities: ["Gauriganj", "Musafirkhana", "Tiloi"] },
      { name: "Amroha", cities: ["Amroha", "Hasanpur", "Gajraula"] },
      { name: "Auraiya", cities: ["Auraiya", "Bidhuna", "Achhalda"] },
      { name: "Ayodhya", cities: ["Ayodhya", "Bikapur", "Milkipur"] },
      { name: "Azamgarh", cities: ["Azamgarh", "Phulpur", "Lalganj"] },
      { name: "Baghpat", cities: ["Baghpat", "Baraut", "Pilana"] },
      { name: "Bahraich", cities: ["Bahraich", "Nanpara", "Kaiserganj"] },
      { name: "Ballia", cities: ["Ballia", "Rasra", "Bairia"] },
      { name: "Balrampur", cities: ["Balrampur", "Utraula", "Tulsipur"] },
      { name: "Banda", cities: ["Banda", "Atarra", "Naraini"] },
      { name: "Barabanki", cities: ["Barabanki", "Fatehpur", "Nawabganj"] },
      { name: "Bareilly", cities: ["Bareilly", "Aonla", "Faridpur"] },
      { name: "Basti", cities: ["Basti", "Harraiya", "Rudhauli"] },
      { name: "Bhadohi", cities: ["Bhadohi", "Gyanpur", "Aurai"] },
      { name: "Bijnor", cities: ["Bijnor", "Nagina", "Dhampur"] },
      { name: "Budaun", cities: ["Budaun", "Bisauli", "Sahaswan"] },
      { name: "Bulandshahr", cities: ["Bulandshahr", "Khurja", "Sikandrabad"] },
      { name: "Chandauli", cities: ["Chandauli", "Mughalsarai", "Chakia"] },
      { name: "Chitrakoot", cities: ["Chitrakoot", "Karvi", "Mau"] },
      { name: "Deoria", cities: ["Deoria", "Salempur", "Barhaj"] },
      { name: "Etah", cities: ["Etah", "Kasganj", "Aliganj"] },
      { name: "Etawah", cities: ["Etawah", "Bharthana", "Chakarnagar"] },
      { name: "Farrukhabad", cities: ["Farrukhabad", "Kaimganj", "Kampil"] },
      { name: "Fatehpur", cities: ["Fatehpur", "Bindki", "Khaga"] },
      { name: "Firozabad", cities: ["Firozabad", "Shikohabad", "Tundla"] },
      { name: "Gautam Buddha Nagar", cities: ["Noida", "Greater Noida", "Dadri"] },
      { name: "Ghaziabad", cities: ["Ghaziabad", "Loni", "Modinagar"] },
      { name: "Ghazipur", cities: ["Ghazipur", "Jakhania", "Saidpur"] },
      { name: "Gonda", cities: ["Gonda", "Colonelganj", "Mankapur"] },
      { name: "Gorakhpur", cities: ["Gorakhpur", "Chauri Chaura", "Sahjanwa"] },
      { name: "Hamirpur", cities: ["Hamirpur", "Rath", "Maudaha"] },
      { name: "Hapur", cities: ["Hapur", "Garmukteshwar", "Dhaulana"] },
      { name: "Hardoi", cities: ["Hardoi", "Shahabad", "Sandila"] },
      { name: "Hathras", cities: ["Hathras", "Sasni", "Sikandra Rao"] },
      { name: "Jalaun", cities: ["Orai", "Konch", "Kalpi"] },
      { name: "Jaunpur", cities: ["Jaunpur", "Shahganj", "Machhlishahr"] },
      { name: "Jhansi", cities: ["Jhansi", "Mauranipur", "Garautha"] },
      { name: "Kannauj", cities: ["Kannauj", "Tirwa", "Chhibramau"] },
      { name: "Kanpur Dehat", cities: ["Akbarpur", "Rasulabad", "Sikandra"] },
      { name: "Kanpur Nagar", cities: ["Kanpur", "Ghatampur", "Bilhaur"] },
      { name: "Kasganj", cities: ["Kasganj", "Sahawar", "Patiyali"] },
      { name: "Kaushambi", cities: ["Manjhanpur", "Sirathu", "Chail"] },
      { name: "Kheri", cities: ["Lakhimpur", "Gola Gokarnath", "Palia Kalan"] },
      { name: "Kushinagar", cities: ["Padrauna", "Kasya", "Tamkuhi Raj"] },
      { name: "Lalitpur", cities: ["Lalitpur", "Talbehat", "Bar"] },
      { name: "Lucknow", cities: ["Lucknow", "Malihabad", "Mohanlalganj"] },
      { name: "Maharajganj", cities: ["Maharajganj", "Nautanwa", "Pharenda"] },
      { name: "Mahoba", cities: ["Mahoba", "Charkhari", "Panwari"] },
      { name: "Mainpuri", cities: ["Mainpuri", "Karhal", "Bhongaon"] },
      { name: "Mathura", cities: ["Mathura", "Vrindavan", "Chhata"] },
      { name: "Mau", cities: ["Mau", "Ghosi", "Madhuban"] },
      { name: "Meerut", cities: ["Meerut", "Mawana", "Sardhana"] },
      { name: "Mirzapur", cities: ["Mirzapur", "Chunar", "Marihan"] },
      { name: "Moradabad", cities: ["Moradabad", "Sambhal", "Thakurdwara"] },
      { name: "Muzaffarnagar", cities: ["Muzaffarnagar", "Shamli", "Kairana"] },
      { name: "Pilibhit", cities: ["Pilibhit", "Puranpur", "Bisalpur"] },
      { name: "Pratapgarh", cities: ["Pratapgarh", "Kunda", "Patti"] },
      { name: "Prayagraj", cities: ["Prayagraj", "Phulpur", "Soraon"] },
      { name: "Raebareli", cities: ["Raebareli", "Lalganj", "Salon"] },
      { name: "Rampur", cities: ["Rampur", "Swar", "Tanda"] },
      { name: "Saharanpur", cities: ["Saharanpur", "Behat", "Deoband"] },
      { name: "Sambhal", cities: ["Sambhal", "Chandausi", "Gunnaur"] },
      { name: "Sant Kabir Nagar", cities: ["Khalilabad", "Mehdawal", "Baghauli"] },
      { name: "Shahjahanpur", cities: ["Shahjahanpur", "Tilhar", "Powayan"] },
      { name: "Shamli", cities: ["Shamli", "Kairana", "Thana Bhawan"] },
      { name: "Shravasti", cities: ["Bhinga", "Ikauna", "Giला"] },
      { name: "Siddharthnagar", cities: ["Naugarh", "Barhni", "Bansi"] },
      { name: "Sitapur", cities: ["Sitapur", "Biswan", "Mahmudabad"] },
      { name: "Sonbhadra", cities: ["Robertsganj", "Duddhi", "Chopan"] },
      { name: "Sultanpur", cities: ["Sultanpur", "Kadipur", "Lambhua"] },
      { name: "Unnao", cities: ["Unnao", "Purwa", "Safipur"] },
      { name: "Varanasi", cities: ["Varanasi", "Pindra", "Cholapur"] },
    ]
  },
  {
    name: "Uttarakhand",
    districts: [
      { name: "Almora", cities: ["Almora", "Ranikhet", "Bhikiyasain"] },
      { name: "Bageshwar", cities: ["Bageshwar", "Kapkot", "Garur"] },
      { name: "Chamoli", cities: ["Gopeshwar", "Joshimath", "Karnaprayag"] },
      { name: "Champawat", cities: ["Champawat", "Tanakpur", "Lohaghat"] },
      { name: "Dehradun", cities: ["Dehradun", "Mussoorie", "Rishikesh"] },
      { name: "Haridwar", cities: ["Haridwar", "Roorkee", "Laksar"] },
      { name: "Nainital", cities: ["Nainital", "Haldwani", "Ramnagar"] },
      { name: "Pauri Garhwal", cities: ["Pauri", "Kotdwar", "Srinagar"] },
      { name: "Pithoragarh", cities: ["Pithoragarh", "Dharchula", "Didihat"] },
      { name: "Rudraprayag", cities: ["Rudraprayag", "Ukhimath", "Augustmuni"] },
      { name: "Tehri Garhwal", cities: ["New Tehri", "Devprayag", "Narendranagar"] },
      { name: "Udham Singh Nagar", cities: ["Rudrapur", "Kashipur", "Kichha"] },
      { name: "Uttarkashi", cities: ["Uttarkashi", "Barkot", "Purola"] },
    ]
  },
  {
    name: "West Bengal",
    districts: [
      { name: "Alipurduar", cities: ["Alipurduar", "Falakata", "Kumargram"] },
      { name: "Bankura", cities: ["Bankura", "Bishnupur", "Khatra"] },
      { name: "Birbhum", cities: ["Suri", "Bolpur", "Rampurhat"] },
      { name: "Cooch Behar", cities: ["Cooch Behar", "Dinhata", "Mathabhanga"] },
      { name: "Dakshin Dinajpur", cities: ["Balurghat", "Gangarampur", "Kumarganj"] },
      { name: "Darjeeling", cities: ["Darjeeling", "Siliguri", "Kalimpong"] },
      { name: "Hooghly", cities: ["Chinsurah", "Chandannagar", "Serampore"] },
      { name: "Howrah", cities: ["Howrah", "Uluberia", "Bagnan"] },
      { name: "Jalpaiguri", cities: ["Jalpaiguri", "Malbazar", "Dhupguri"] },
      { name: "Jhargram", cities: ["Jhargram", "Belpahari", "Gopiballavpur"] },
      { name: "Kalimpong", cities: ["Kalimpong", "Lava", "Pedong"] },
      { name: "Kolkata", cities: ["Kolkata", "New Alipore", "Behala"] },
      { name: "Malda", cities: ["Malda", "English Bazar", "Old Malda"] },
      { name: "Murshidabad", cities: ["Baharampur", "Kandi", "Jangipur"] },
      { name: "Nadia", cities: ["Krishnanagar", "Ranaghat", "Kalyani"] },
      { name: "North 24 Parganas", cities: ["Barasat", "Barrackpore", "Basirhat"] },
      { name: "Paschim Bardhaman", cities: ["Asansol", "Durgapur", "Raniganj"] },
      { name: "Paschim Medinipur", cities: ["Midnapore", "Kharagpur", "Ghatal"] },
      { name: "Purba Bardhaman", cities: ["Bardhaman", "Katwa", "Kalna"] },
      { name: "Purba Medinipur", cities: ["Tamluk", "Contai", "Haldia"] },
      { name: "Purulia", cities: ["Purulia", "Raghunathpur", "Jhalda"] },
      { name: "South 24 Parganas", cities: ["Alipore", "Baruipur", "Diamond Harbour"] },
      { name: "Uttar Dinajpur", cities: ["Raiganj", "Islampur", "Kaliyaganj"] },
    ]
  },
  {
    name: "Andaman and Nicobar Islands",
    districts: [
      { name: "Nicobar", cities: ["Car Nicobar", "Nancowry", "Campbell Bay"] },
      { name: "North and Middle Andaman", cities: ["Mayabunder", "Rangat", "Diglipur"] },
      { name: "South Andaman", cities: ["Port Blair", "Bamboo Flat", "Ferrargunj"] },
    ]
  },
  {
    name: "Chandigarh",
    districts: [
      { name: "Chandigarh", cities: ["Sector 17", "Sector 22", "Manimajra"] },
    ]
  },
  {
    name: "Dadra and Nagar Haveli and Daman and Diu",
    districts: [
      { name: "Dadra and Nagar Haveli", cities: ["Silvassa", "Amli", "Khanvel"] },
      { name: "Daman", cities: ["Daman", "Nani Daman", "Moti Daman"] },
      { name: "Diu", cities: ["Diu", "Ghogla", "Fudam"] },
    ]
  },
  {
    name: "Jammu and Kashmir",
    districts: [
      { name: "Anantnag", cities: ["Anantnag", "Pahalgam", "Mattan"] },
      { name: "Bandipora", cities: ["Bandipora", "Sumbal", "Gurez"] },
      { name: "Baramulla", cities: ["Baramulla", "Sopore", "Uri"] },
      { name: "Budgam", cities: ["Budgam", "Beerwah", "Chadoora"] },
      { name: "Doda", cities: ["Doda", "Bhaderwah", "Thathri"] },
      { name: "Ganderbal", cities: ["Ganderbal", "Kangan", "Lar"] },
      { name: "Jammu", cities: ["Jammu", "Akhnoor", "Bishnah"] },
      { name: "Kathua", cities: ["Kathua", "Hiranagar", "Billawar"] },
      { name: "Kishtwar", cities: ["Kishtwar", "Paddar", "Chatroo"] },
      { name: "Kulgam", cities: ["Kulgam", "Devsar", "Frisal"] },
      { name: "Kupwara", cities: ["Kupwara", "Handwara", "Karnah"] },
      { name: "Poonch", cities: ["Poonch", "Surankote", "Mendhar"] },
      { name: "Pulwama", cities: ["Pulwama", "Shopian", "Tral"] },
      { name: "Rajouri", cities: ["Rajouri", "Nowshera", "Kalakote"] },
      { name: "Ramban", cities: ["Ramban", "Banihal", "Gool"] },
      { name: "Reasi", cities: ["Reasi", "Katra", "Gool Gulabgarh"] },
      { name: "Samba", cities: ["Samba", "Vijaypur", "Ghagwal"] },
      { name: "Shopian", cities: ["Shopian", "Zainpora", "Kellar"] },
      { name: "Srinagar", cities: ["Srinagar", "Pampore", "Shupiyan"] },
      { name: "Udhampur", cities: ["Udhampur", "Ramnagar", "Chenani"] },
    ]
  },
  {
    name: "Ladakh",
    districts: [
      { name: "Kargil", cities: ["Kargil", "Drass", "Zanskar"] },
      { name: "Leh", cities: ["Leh", "Nubra", "Khaltsi"] },
    ]
  },
  {
    name: "Lakshadweep",
    districts: [
      { name: "Lakshadweep", cities: ["Kavaratti", "Agatti", "Minicoy"] },
    ]
  },
  {
    name: "Puducherry",
    districts: [
      { name: "Karaikal", cities: ["Karaikal", "Thirunallar", "Nedungadu"] },
      { name: "Mahe", cities: ["Mahe", "Palloor", "Chalakara"] },
      { name: "Puducherry", cities: ["Puducherry", "Ozhukarai", "Villianur"] },
      { name: "Yanam", cities: ["Yanam", "Mettakur", "Kamepalli"] },
    ]
  },
];

export const getDistrictsByState = (stateName: string): District[] => {
  const state = INDIAN_STATES.find(s => s.name === stateName);
  return state?.districts || [];
};

export const getCitiesByDistrict = (stateName: string, districtName: string): string[] => {
  const state = INDIAN_STATES.find(s => s.name === stateName);
  const district = state?.districts.find(d => d.name === districtName);
  return district?.cities || [];
};
