import { serve } from "https://deno.land/std@0.190.0/http/server.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
};

interface CreditReportEmailRequest {
  recipientEmail: string;
  companyName: string;
  gstin: string;
  reportData: Record<string, any>;
  selectedReports: string[];
}

const handler = async (req: Request): Promise<Response> => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const resendApiKey = Deno.env.get("RESEND_API_KEY");
    
    if (!resendApiKey) {
      console.error("RESEND_API_KEY not configured");
      return new Response(
        JSON.stringify({ error: "Email service not configured. Please add RESEND_API_KEY." }),
        {
          status: 500,
          headers: { "Content-Type": "application/json", ...corsHeaders },
        }
      );
    }

    const { recipientEmail, companyName, gstin, reportData, selectedReports }: CreditReportEmailRequest = await req.json();

    console.log("Sending credit report email to:", recipientEmail);

    // Build report sections HTML
    let reportSectionsHtml = "";
    
    for (const reportKey of selectedReports) {
      const data = reportData[reportKey];
      if (data) {
        reportSectionsHtml += `
          <div style="margin-bottom: 20px; padding: 15px; background: #f8f9fa; border-radius: 8px;">
            <h3 style="color: #1a1a2e; margin-bottom: 10px; border-bottom: 2px solid #4361ee; padding-bottom: 5px;">
              ${formatReportName(reportKey)}
            </h3>
            <div style="font-size: 14px; color: #333;">
              ${formatReportData(data)}
            </div>
          </div>
        `;
      }
    }

    const emailHtml = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <title>MSME Credit Report - ${companyName}</title>
      </head>
      <body style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; background-color: #f5f5f5;">
        <div style="background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%); color: white; padding: 30px; border-radius: 10px 10px 0 0;">
          <h1 style="margin: 0; font-size: 24px;">MSME Credit Report</h1>
          <p style="margin: 10px 0 0 0; opacity: 0.9;">Generated on ${new Date().toLocaleDateString('en-IN', { dateStyle: 'long' })}</p>
        </div>
        
        <div style="background: white; padding: 30px; border-radius: 0 0 10px 10px; box-shadow: 0 4px 6px rgba(0,0,0,0.1);">
          <div style="background: #e8f4fd; padding: 20px; border-radius: 8px; margin-bottom: 25px;">
            <h2 style="color: #1a1a2e; margin: 0 0 15px 0;">Company Information</h2>
            <table style="width: 100%; border-collapse: collapse;">
              <tr>
                <td style="padding: 8px 0; color: #666; width: 40%;">Company Name:</td>
                <td style="padding: 8px 0; color: #333; font-weight: 600;">${companyName}</td>
              </tr>
              <tr>
                <td style="padding: 8px 0; color: #666;">GSTIN:</td>
                <td style="padding: 8px 0; color: #333; font-weight: 600;">${gstin}</td>
              </tr>
              <tr>
                <td style="padding: 8px 0; color: #666;">Reports Included:</td>
                <td style="padding: 8px 0; color: #333; font-weight: 600;">${selectedReports.length} report(s)</td>
              </tr>
            </table>
          </div>
          
          <h2 style="color: #1a1a2e; border-bottom: 2px solid #4361ee; padding-bottom: 10px;">Report Details</h2>
          ${reportSectionsHtml}
          
          <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #eee; text-align: center; color: #666; font-size: 12px;">
            <p>This report was generated by Solviser ERP System</p>
            <p>For any queries, please contact support</p>
          </div>
        </div>
      </body>
      </html>
    `;

    // Send email using Resend API directly
    const response = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${resendApiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        from: "Solviser <onboarding@resend.dev>",
        to: [recipientEmail],
        subject: `MSME Credit Report - ${companyName} (${gstin})`,
        html: emailHtml,
      }),
    });

    const emailResponse = await response.json();

    if (!response.ok) {
      console.error("Resend API error:", emailResponse);
      throw new Error(emailResponse.message || "Failed to send email");
    }

    console.log("Email sent successfully:", emailResponse);

    return new Response(JSON.stringify({ success: true, data: emailResponse }), {
      status: 200,
      headers: { "Content-Type": "application/json", ...corsHeaders },
    });
  } catch (error: any) {
    console.error("Error sending credit report email:", error);
    return new Response(
      JSON.stringify({ error: error.message }),
      {
        status: 500,
        headers: { "Content-Type": "application/json", ...corsHeaders },
      }
    );
  }
};

function formatReportName(key: string): string {
  const names: Record<string, string> = {
    gst_compliance: "GST Compliance Score",
    gst_filing: "GST Filing History",
    financial_health: "Financial Health Analysis",
    payment_behavior: "Payment Behavior Analysis",
    credit_utilization: "Credit Utilization",
    bank_statements: "Bank Statement Analysis",
    industry_benchmark: "Industry Benchmarking",
    risk_assessment: "Risk Assessment",
    supplier_analysis: "Supplier Analysis",
    legal_compliance: "Legal & Regulatory Compliance",
    business_stability: "Business Stability Score",
    growth_potential: "Growth Potential Analysis",
  };
  return names[key] || key.replace(/_/g, " ").replace(/\b\w/g, (l) => l.toUpperCase());
}

function formatReportData(data: any): string {
  if (typeof data === "object" && data !== null) {
    let html = "<ul style='margin: 0; padding-left: 20px;'>";
    for (const [key, value] of Object.entries(data)) {
      const formattedKey = key.replace(/_/g, " ").replace(/\b\w/g, (l) => l.toUpperCase());
      html += `<li style="margin: 5px 0;"><strong>${formattedKey}:</strong> ${formatValue(value)}</li>`;
    }
    html += "</ul>";
    return html;
  }
  return String(data);
}

function formatValue(value: any): string {
  if (typeof value === "number") {
    return value.toLocaleString("en-IN");
  }
  if (Array.isArray(value)) {
    return value.join(", ");
  }
  if (typeof value === "object" && value !== null) {
    return JSON.stringify(value);
  }
  return String(value);
}

serve(handler);
